'use strict';

/** Replace {{var}} placeholders with values from vars map. */
function interpolate(text, vars) {
  return text.replace(/\{\{(\w+)\}\}/g, (_match, key) => {
    if (key in vars) return vars[key];
    return `{{${key}}}`;
  });
}

/** Check for unresolved {{...}} placeholders. */
function findUnresolved(text) {
  const matches = text.match(/\{\{(\w+)\}\}/g);
  return matches ? [...new Set(matches)] : [];
}

function normalizeListSection(value) {
  if (Array.isArray(value)) {
    return value
      .map((item) => String(item).trim())
      .filter(Boolean)
      .map((item) => (item.startsWith('- ') ? item : `- ${item}`))
      .join('\n');
  }

  if (typeof value === 'string') {
    return value.trim();
  }

  return '';
}

function getClaudeCodeConfig(projectConfig) {
  const legacy = projectConfig.claude_code || {};
  const append = (projectConfig.overrides || {}).claude_code_append || {};
  return { ...legacy, ...append };
}

function getPerplexitySpaceConfig(projectConfig) {
  const append = (projectConfig.overrides || {}).perplexity_space_append || {};
  const researchDomains = normalizeListSection(append.research_domains) || normalizeListSection(projectConfig.research_domains);
  return { ...append, research_domains: researchDomains };
}

function assembleClaudeCode(blocks, projectConfig, vars) {
  const lines = [];
  const today = new Date().toISOString().slice(0, 10);
  lines.push(`# ${vars.project || vars.repo_name || 'Project'}`);
  lines.push(`<!-- Generated by Praxis prompt-compile | profile: ${projectConfig.profile} | ${today} -->`);
  lines.push('');

  // Identity
  const identityBlocks = blocks.filter((b) => b.category === 'identity');
  if (identityBlocks.length > 0) {
    lines.push('## Identity');
    for (const block of identityBlocks) lines.push(block.content, '');
  }

  // Global Rules reference
  lines.push('## Global Rules');
  lines.push('Inherits execution engine from `~/.claude/CLAUDE.md`.');
  lines.push('');

  // Git Identity
  const append = getClaudeCodeConfig(projectConfig);
  const gitEmail = append.git_email || vars.git_email;
  const gitIdentity = append.git_identity || vars.git_identity;
  if (gitEmail || gitIdentity) {
    lines.push('## Git Identity');
    if (gitIdentity) lines.push(`- **Type**: ${gitIdentity}`);
    if (gitEmail) lines.push(`- **Email**: ${gitEmail}`);
    lines.push('');
  }

  // Behaviors
  const behaviorBlocks = blocks.filter((b) => b.category === 'behaviors');
  if (behaviorBlocks.length > 0) {
    lines.push('## Behaviors');
    for (const block of behaviorBlocks) lines.push(block.content, '');
  }

  // Domains
  const domainBlocks = blocks.filter((b) => b.category === 'domains');
  if (domainBlocks.length > 0) {
    lines.push('## Domain Expertise');
    for (const block of domainBlocks) lines.push(block.content, '');
  }

  // Skills
  const skillBlocks = blocks.filter((b) => b.category === 'skills');
  if (skillBlocks.length > 0) {
    lines.push('## Skills & Techniques');
    for (const block of skillBlocks) lines.push(block.content, '');
  }

  // Formats
  const formatBlocks = blocks.filter((b) => b.category === 'formats');
  if (formatBlocks.length > 0) {
    lines.push('## Output Format');
    for (const block of formatBlocks) lines.push(block.content, '');
  }

  // Tech Stack + Commands
  if (append.tech_stack) {
    lines.push('## Tech Stack');
    lines.push(append.tech_stack.trim(), '');
  }
  if (append.commands) {
    lines.push('## Commands');
    lines.push('```bash');
    lines.push(append.commands.trim());
    lines.push('```', '');
  }

  // Context
  const contextBlocks = blocks.filter((b) => b.category === 'context');
  if (contextBlocks.length > 0) {
    for (const block of contextBlocks) lines.push(block.content, '');
  }

  // Extra notes
  if (append.extra_notes) {
    lines.push('## Important Notes');
    lines.push(append.extra_notes.trim(), '');
  }

  // Standard footer
  lines.push('## Verification');
  lines.push('- Before marking any task complete, run the test suite');
  lines.push('- Check logs before claiming a bug is fixed');
  lines.push('');
  lines.push('## Conventions');
  lines.push('- **Commits**: conventional commits (feat:, fix:, docs:, refactor:, test:, chore:)');
  lines.push('- **Branches**: `feat/description` or `fix/description`');
  lines.push('');
  lines.push('## Error Learning');
  lines.push('<!-- Add project-specific learnings below -->');
  lines.push('');

  return lines.join('\n');
}

function assembleClaudeProject(blocks, projectConfig, vars) {
  const lines = [];

  // Layer 1: Role
  const identityBlocks = blocks.filter((b) => b.category === 'identity');
  lines.push('## Role');
  if (projectConfig.description) lines.push(projectConfig.description);
  for (const block of identityBlocks) lines.push(block.content);
  lines.push('');

  // Layer 2: Behavioral Constraints
  const behaviorBlocks = blocks.filter((b) => b.category === 'behaviors');
  if (behaviorBlocks.length > 0) {
    lines.push('## Behavioral Constraints');
    for (const block of behaviorBlocks) lines.push(block.content, '');
  }

  // Layer 3: Domain Expertise
  const domainBlocks = blocks.filter((b) => b.category === 'domains');
  if (domainBlocks.length > 0) {
    lines.push('## Domain Expertise');
    for (const block of domainBlocks) lines.push(block.content, '');
  }

  // Layer 3a: Skills & Techniques
  const skillBlocks = blocks.filter((b) => b.category === 'skills');
  if (skillBlocks.length > 0) {
    lines.push('## Skills & Techniques');
    for (const block of skillBlocks) lines.push(block.content, '');
  }

  // Layer 3b: Output Format
  const formatBlocks = blocks.filter((b) => b.category === 'formats');
  if (formatBlocks.length > 0) {
    lines.push('## Output Format');
    for (const block of formatBlocks) lines.push(block.content, '');
  }

  // Deal context — auto-injected from deal config vars
  if (projectConfig.deal && vars.agency) {
    lines.push('## Deal Context');
    lines.push(`**Customer**: ${vars.agency}`);
    if (vars.program_name) lines.push(`**Program**: ${vars.program_name}`);
    if (vars.incumbent) lines.push(`**Incumbent**: ${vars.incumbent}`);
    if (vars.contract_value) lines.push(`**Value**: ${vars.contract_value}`);
    if (vars.naics) lines.push(`**NAICS**: ${vars.naics}`);
    if (vars.pop) lines.push(`**POP**: ${vars.pop}`);
    if (projectConfig.deal_type) lines.push(`**Type**: ${projectConfig.deal_type}`);
    if (projectConfig.capture_phase) lines.push(`**Phase**: ${projectConfig.capture_phase}`);
    lines.push('');
  }

  // Additional context
  const append = (projectConfig.overrides || {}).claude_project_append || {};
  if (append.additional_context) {
    lines.push(append.additional_context.trim(), '');
  }

  // Layer 4: Quality Gates
  if (append.quality_gates) {
    lines.push('## Quality Gates');
    lines.push(append.quality_gates.trim(), '');
  }

  // Context blocks (workflow, etc.)
  const contextBlocks = blocks.filter((b) => b.category === 'context');
  if (contextBlocks.length > 0) {
    for (const block of contextBlocks) lines.push(block.content);
    lines.push('');
  }

  // Layer 4b: Knowledge Files (if project has them)
  const knowledgeFiles = projectConfig.knowledge_files || [];
  if (knowledgeFiles.length > 0) {
    lines.push('## Knowledge Files');
    lines.push('Upload these alongside this prompt:');
    for (const kf of knowledgeFiles) {
      lines.push(`- **${kf.file}** — ${kf.description}`);
    }
    lines.push('');
  }

  // Layer 5: Failure Handling (always present)
  lines.push('## When Uncertain');
  lines.push('State uncertainty explicitly. Ask one clarifying question rather than guessing.');
  lines.push('');

  return lines.join('\n');
}

function assemblePerplexitySpace(blocks, projectConfig, vars) {
  const lines = [];

  // Purpose — identity only (no domain blocks, no skills, no behaviors)
  // Perplexity is a search engine, not a generative AI. It needs to know
  // WHAT to research and HOW to format answers, not what it's "expert" in.
  lines.push('## Purpose');
  if (projectConfig.description) lines.push(projectConfig.description);
  lines.push('');

  // Deal context — auto-injected from deal config vars
  if (projectConfig.deal && vars.agency) {
    lines.push('## Deal Context');
    lines.push(`Customer: ${vars.agency}`);
    if (vars.program_name) lines.push(`Program: ${vars.program_name}`);
    if (vars.incumbent) lines.push(`Incumbent: ${vars.incumbent}`);
    if (vars.contract_value) lines.push(`Value: ${vars.contract_value}`);
    if (projectConfig.deal_type) lines.push(`Type: ${projectConfig.deal_type}`);
    if (projectConfig.capture_phase) lines.push(`Phase: ${projectConfig.capture_phase}`);
    lines.push('');
  }

  // Research Domains — what Perplexity should search for
  const append = getPerplexitySpaceConfig(projectConfig);
  if (append.research_domains) {
    lines.push('## Research Domains');
    lines.push(append.research_domains.trim(), '');
  }

  // How to Answer — concise, search-oriented instructions
  lines.push('## How to Answer');
  lines.push('Lead with the answer, then supporting evidence and sources.');
  lines.push('Use tables for comparisons. Use numbered steps for procedures.');
  lines.push('Structure every response: answer first, reasoning second, sources third.');
  lines.push('Flag confidence: HIGH (multiple sources), MEDIUM (single source), LOW (inferred).');
  lines.push('');

  // Accuracy Standards — anti-hallucination for search results
  lines.push('## Accuracy Standards');
  lines.push('- Distinguish verified facts from analytical inferences');
  lines.push('- If sources disagree, cite both and explain the discrepancy');
  lines.push('- Never fabricate version numbers, statistics, citations, or URLs');
  lines.push('- When information may be outdated (>12 months), note the publication date');
  lines.push('- If you cannot find reliable sources, state that clearly rather than speculating');
  lines.push('');

  return lines.join('\n');
}

module.exports = {
  interpolate,
  findUnresolved,
  assembleClaudeCode,
  assembleClaudeProject,
  assemblePerplexitySpace,
};
