'use strict';

/** Replace {{var}} placeholders with values from vars map. */
function interpolate(text, vars) {
  return text.replace(/\{\{(\w+)\}\}/g, (_match, key) => {
    if (key in vars) return vars[key];
    return `{{${key}}}`;
  });
}

/** Check for unresolved {{...}} placeholders. */
function findUnresolved(text) {
  const matches = text.match(/\{\{(\w+)\}\}/g);
  return matches ? [...new Set(matches)] : [];
}

function assembleClaudeCode(blocks, projectConfig, vars) {
  const lines = [];
  const today = new Date().toISOString().slice(0, 10);
  lines.push(`# ${vars.project || vars.repo_name || 'Project'}`);
  lines.push(`<!-- Generated by Praxis prompt-compile | profile: ${projectConfig.profile} | ${today} -->`);
  lines.push('');

  // Identity
  const identityBlocks = blocks.filter((b) => b.category === 'identity');
  if (identityBlocks.length > 0) {
    lines.push('## Identity');
    for (const block of identityBlocks) lines.push(block.content, '');
  }

  // Global Rules reference
  lines.push('## Global Rules');
  lines.push('Inherits execution engine from `~/.claude/CLAUDE.md`.');
  lines.push('');

  // Git Identity
  if (vars.git_email || vars.git_identity) {
    lines.push('## Git Identity');
    if (vars.git_identity) lines.push(`- **Type**: ${vars.git_identity}`);
    if (vars.git_email) lines.push(`- **Email**: ${vars.git_email}`);
    lines.push('');
  }

  // Behaviors
  const behaviorBlocks = blocks.filter((b) => b.category === 'behaviors');
  if (behaviorBlocks.length > 0) {
    lines.push('## Behaviors');
    for (const block of behaviorBlocks) lines.push(block.content, '');
  }

  // Domains
  const domainBlocks = blocks.filter((b) => b.category === 'domains');
  if (domainBlocks.length > 0) {
    lines.push('## Domain Expertise');
    for (const block of domainBlocks) lines.push(block.content, '');
  }

  // Skills
  const skillBlocks = blocks.filter((b) => b.category === 'skills');
  if (skillBlocks.length > 0) {
    lines.push('## Skills & Techniques');
    for (const block of skillBlocks) lines.push(block.content, '');
  }

  // Formats
  const formatBlocks = blocks.filter((b) => b.category === 'formats');
  if (formatBlocks.length > 0) {
    lines.push('## Output Format');
    for (const block of formatBlocks) lines.push(block.content, '');
  }

  // Tech Stack + Commands (from claude_code_append)
  const append = (projectConfig.overrides || {}).claude_code_append || {};
  if (append.tech_stack) {
    lines.push('## Tech Stack');
    lines.push(append.tech_stack.trim(), '');
  }
  if (append.commands) {
    lines.push('## Commands');
    lines.push('```bash');
    lines.push(append.commands.trim());
    lines.push('```', '');
  }

  // Context
  const contextBlocks = blocks.filter((b) => b.category === 'context');
  if (contextBlocks.length > 0) {
    for (const block of contextBlocks) lines.push(block.content, '');
  }

  // Extra notes
  if (append.extra_notes) {
    lines.push('## Important Notes');
    lines.push(append.extra_notes.trim(), '');
  }

  // Standard footer
  lines.push('## Verification');
  lines.push('- Before marking any task complete, run the test suite');
  lines.push('- Check logs before claiming a bug is fixed');
  lines.push('');
  lines.push('## Conventions');
  lines.push('- **Commits**: conventional commits (feat:, fix:, docs:, refactor:, test:, chore:)');
  lines.push('- **Branches**: `feat/description` or `fix/description`');
  lines.push('');
  lines.push('## Error Learning');
  lines.push('<!-- Add project-specific learnings below -->');
  lines.push('');

  return lines.join('\n');
}

function assembleClaudeProject(blocks, projectConfig, vars) {
  const lines = [];

  // Layer 1: Role
  const identityBlocks = blocks.filter((b) => b.category === 'identity');
  lines.push('## Role');
  if (projectConfig.description) lines.push(projectConfig.description);
  for (const block of identityBlocks) lines.push(block.content);
  lines.push('');

  // Layer 2: Behavioral Constraints
  const behaviorBlocks = blocks.filter((b) => b.category === 'behaviors');
  if (behaviorBlocks.length > 0) {
    lines.push('## Behavioral Constraints');
    for (const block of behaviorBlocks) lines.push(block.content, '');
  }

  // Layer 3: Domain Expertise
  const domainBlocks = blocks.filter((b) => b.category === 'domains');
  if (domainBlocks.length > 0) {
    lines.push('## Domain Expertise');
    for (const block of domainBlocks) lines.push(block.content, '');
  }

  // Layer 3a: Skills & Techniques
  const skillBlocks = blocks.filter((b) => b.category === 'skills');
  if (skillBlocks.length > 0) {
    lines.push('## Skills & Techniques');
    for (const block of skillBlocks) lines.push(block.content, '');
  }

  // Layer 3b: Output Format
  const formatBlocks = blocks.filter((b) => b.category === 'formats');
  if (formatBlocks.length > 0) {
    lines.push('## Output Format');
    for (const block of formatBlocks) lines.push(block.content, '');
  }

  // Additional context
  const append = (projectConfig.overrides || {}).claude_project_append || {};
  if (append.additional_context) {
    lines.push(append.additional_context.trim(), '');
  }

  // Layer 4: Quality Gates
  if (append.quality_gates) {
    lines.push('## Quality Gates');
    lines.push(append.quality_gates.trim(), '');
  }

  // Context blocks (workflow, etc.)
  const contextBlocks = blocks.filter((b) => b.category === 'context');
  if (contextBlocks.length > 0) {
    for (const block of contextBlocks) lines.push(block.content);
    lines.push('');
  }

  // Layer 4b: Knowledge Files (if project has them)
  const knowledgeFiles = projectConfig.knowledge_files || [];
  if (knowledgeFiles.length > 0) {
    lines.push('## Knowledge Files');
    lines.push('Upload these alongside this prompt:');
    for (const kf of knowledgeFiles) {
      lines.push(`- **${kf.file}** — ${kf.description}`);
    }
    lines.push('');
  }

  // Layer 5: Failure Handling (always present)
  lines.push('## When Uncertain');
  lines.push('State uncertainty explicitly. Ask one clarifying question rather than guessing.');
  lines.push('');

  return lines.join('\n');
}

function assemblePerplexitySpace(blocks, projectConfig, vars) {
  const lines = [];

  // Purpose
  const identityBlocks = blocks.filter((b) => b.category === 'identity');
  lines.push('## Purpose');
  if (projectConfig.description) lines.push(projectConfig.description);
  for (const block of identityBlocks) lines.push(block.content);
  lines.push('');

  // Source Priority
  const sourceBlocks = blocks.filter(
    (b) => b.category === 'context' && (b.meta.tags || []).includes('sources')
  );
  if (sourceBlocks.length > 0) {
    lines.push('## Source Priority');
    for (const block of sourceBlocks) lines.push(block.content);
    lines.push('');
  }

  // Domain Expertise
  const domainBlocks = blocks.filter((b) => b.category === 'domains');
  if (domainBlocks.length > 0) {
    lines.push('## Domain Expertise');
    for (const block of domainBlocks) lines.push(block.content);
    lines.push('');
  }

  // Capabilities (skills)
  const skillBlocks = blocks.filter((b) => b.category === 'skills');
  if (skillBlocks.length > 0) {
    lines.push('## Capabilities');
    for (const block of skillBlocks) lines.push(block.content);
    lines.push('');
  }

  // Research Domains
  const append = (projectConfig.overrides || {}).perplexity_space_append || {};
  if (append.research_domains) {
    lines.push('## Research Domains');
    lines.push(append.research_domains.trim(), '');
  }

  // How to Answer
  const behaviorBlocks = blocks.filter((b) => b.category === 'behaviors');
  const formatBlocks = blocks.filter((b) => b.category === 'formats');
  if (behaviorBlocks.length > 0 || formatBlocks.length > 0) {
    lines.push('## How to Answer');
    for (const block of behaviorBlocks) lines.push(block.content);
    for (const block of formatBlocks) lines.push(block.content);
    lines.push('');
  }

  // Anti-hallucination layer (auto-injected for all Perplexity outputs)
  lines.push('## Accuracy Standards');
  lines.push('- Flag your confidence level when synthesizing across sources');
  lines.push('- Distinguish verified facts from analytical inferences');
  lines.push('- If sources disagree, cite both and explain the discrepancy');
  lines.push('- Never fabricate version numbers, API signatures, URLs, or code examples');
  lines.push('- When information may be outdated (>12 months), note the publication date');
  lines.push('- If you cannot find reliable sources, state that clearly rather than speculating');
  lines.push('');

  return lines.join('\n');
}

module.exports = {
  interpolate,
  findUnresolved,
  assembleClaudeCode,
  assembleClaudeProject,
  assemblePerplexitySpace,
};
